### ISSUE TITLE
Handle port configured but not available

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#125]
Currently, if a port is configured but the port isn't available (for example, the USB adapter isn't plugged in) the app generates an error that doesn't look appropriate to a user.

The app should check the port, and if it's not available, print a friendly status message indicating that the configured port wasn't found and key & sounder functionality won't be available.

**Comment by leskerr** [comment]
I get this error now when I don't have my USB adapter plugged in:

```
C:\Users\Les\Documents\GitHub\PyKOB\MKOB>py mkob.pyw
Traceback (most recent call last):
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\pykob\kob.py", line 60, in __init__
    self.port = serial.Serial(port)
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mkob.pyw", line 35, in <module>
    import kobwindow
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobwindow.py", line 34, in <module>
    import kobactions as ka
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobactions.py", line 36, in <module>
    import kobmain as km
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobmain.py", line 191, in <module>
    callback=from_KOB if kc.config.sounder else None)
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\pykob\kob.py", line 63, in __init__
    log.info('Interface for key and sounder on serial port {} not available. Key and sounder will not be used.'.format(port))
AttributeError: module 'pykob.log' has no attribute 'info'
```

**Comment by AESilky** [comment]
Was able to replicate the issue using a port of `/dev/ttyXYZZY'.
