### ISSUE TITLE
'txtKeyboard' error message on startup

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#143]
Sometimes, when first starting MKOB, the following error message appears:
```
PyKOB 1.2.9
MorseKOB 4.0.11
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/les/PyKOB/MKOB/kobkeyboard.py", line 45, in keyboard_send
    kw.txtKeyboard.tag_config('highlight', background='gray75',
AttributeError: 'KOBWindow' object has no attribute 'txtKeyboard'
```

Usually restarting the program makes the error go away. It seems to happen with low-end computers that may have performance issues.

**Comment by AESilky** [comment]
I think this has been fixed. I haven't seen it for quite some time.
