### ISSUE TITLE
Check for internet availability

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#156]
There are times when users want to run MKOB in a local configuration, without any internet connection. Currently, the program crashes on startup if there's no internet.

```
C:\Users\Les\Documents\GitHub\PyKOB\MKOB>py mkob.pyw
2020-10-06 23:00:07     INFO:   Interface for key and/or sounder on serial port 'com10' not available. Key and sounder will not be used.
Traceback (most recent call last):
  File "mkob.pyw", line 35, in <module>
    import kobwindow
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobwindow.py", line 34, in <module>
    import kobactions as ka
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobactions.py", line 36, in <module>
    import kobmain as km
  File "C:\Users\Les\Documents\GitHub\PyKOB\MKOB\kobmain.py", line 225, in <module>
    myInternet = internet.Internet(kc.config.station, callback=from_internet)
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\site-packages\pykob\internet.py", line 55, in __init__
    socket.SOCK_DGRAM)[0][4]
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by AESilky** [comment]
*pykob.internet* checks for network availability and provides a method to check it. MKOB and MRT use the method to allow operation when internet connectivity isn't available. This allows practice even when not connected. If the internet connection drops while connected, the *internet* class handles it gracefully and will reconnect when possible.

**pykob version 1.3.4**
**MRT 1.3.5**
**MKOB 4.3.1**
