### ISSUE TITLE
Uninitialized preferences cause crash at startup

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#237]
A fresh install of MKOB, without explicitly running Configure.py first, defaults the 'wire' setting to a blank string.  This causes a crash at startup when kobwindow.py tries to initialize self.spnWireNo by inserting "int(config.wire)" on line 223:

![image](https://user-images.githubusercontent.com/48630827/104820735-bd500080-57eb-11eb-9938-741ba50a153e.png)

**Comment by AESilky** [comment]
I thought I handled that in my changes to config.py. I'll take a look later tonight.

**Comment by pwdirks** [comment]
Having sync'ed with the master branch, it now fails in a different way:

2021-01-16 15:24:48 ERROR: 	Wire option value 'invalid literal for int() with base 10: ''' is not a valid value. INI file key: WIRE.
invalid literal for int() with base 10: ''
2021-01-16 15:24:48 ERROR:	Wire option value 'invalid literal for int() with base 10: ''' is not a valid value. INI file key: WIRE.
invalid literal for int() with base 10: ''
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
Traceback (most recent call last):
  File "MKOB.pyw", line 35, in <module>
    import kobwindow
  File "/mnt/hgfs/Patrick/Documents/Projects/Morse/MorseKOB/PyKOB/kobwindow.py", line 32, in <module>
    import kobmain
  File "/mnt/hgfs/Patrick/Documents/Projects/Morse/MorseKOB/PyKOB/kobmain.py", line 34, in <module>
    from pykob import kob, morse, internet, config, recorder, log
  File "/mnt/hgfs/Patrick/Documents/Projects/Morse/MorseKOB/PyKOB/pykob/kob.py", line 35, in <module>
    from pykob import audio, config, log
  File "/mnt/hgfs/Patrick/Documents/Projects/Morse/MorseKOB/PyKOB/pykob/config.py", line 773, in <module>
    read_config()
  File "/mnt/hgfs/Patrick/Documents/Projects/Morse/MorseKOB/PyKOB/pykob/config.py", line 764, in read_config
    wire = int(_wire)
ValueError: invalid literal for int() with base 10: ''

**Comment by pwdirks** [comment]
Resolved w. merge of fix for #239.
