### ISSUE TITLE
MKOB: preferences panel disappears

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#257]
If you close the preferences window by clicking on the X instead of the Cancel button, then you can't get the preferences panel back again by going to the 'File > Preferences...' menu item.

**Comment by AESilky** [comment]
After closing with the **X** and then using **File | Preferences** causes this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\aesil\proj\pk-mrt\PyKOB\mkobactions.py", line 112, in doFilePreferences
    self._preferencesDialog.root.deiconify()
  File "c:\Program Files\Python311\Lib\tkinter\__init__.py", line 2069, in wm_deiconify
    return self.tk.call('wm', 'deiconify', self._w)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!toplevel"
```
